In [42]:
import numpy as np

In [ ]:
#projectbyPS||__||

In [46]:
def check(x, y, num):
    global grid
    for i in range(9):
        if (grid[x][i] == num):# column
            return False
    for i in range(9):
        if (grid[i][y] == num):#row
            return False
    qx = quad(x)
    qy = quad(y)
    for i in range(qx,qx+3):
        for j in range(qy,qy+3):
            if (grid[i][j] == num):
                return False
    return True


In [47]:
def quad(loc):
    q = 0
    if (loc >= 0 and loc <= 2) :
        q = 0    
    if (loc >= 3 and loc <= 5) :
        q = 3
    if (loc >= 6 and loc <= 8) :
        q = 6

    return q


In [48]:
def solve():
    global grid
    for y in range(9):
        for x in range(9):
            if grid[y][x] == 0:
                for n in range(1,10):
                    if check(y,x,n):
                        grid[y][x] = n
                        solve()
                        grid[y][x] = 0
                return
#     printmat()
    print (np.matrix(grid))
    input("more??")

In [55]:
grid=[[ 3, 0, 6, 5, 0, 0, 4, 0, 0 ], [ 5, 2, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 8, 7, 0, 0, 0, 0, 3, 1 ],
[ 0, 0, 3, 0, 1, 0, 0, 8, 0 ], [ 9, 0, 0, 8, 6, 3, 0, 0, 5 ], [ 0, 5, 0, 0, 0, 0, 6, 0, 0 ],
[ 1, 3, 0, 0, 0, 0, 2, 0 ,0 ], [ 0, 0, 0, 0, 0, 0, 0, 7, 4 ], [ 0, 0, 5, 2, 0, 6, 3, 0, 0 ]]

In [56]:
solve()

[[3 1 6 5 7 8 4 2 9]
 [5 2 9 1 3 4 8 6 7]
 [4 8 7 6 9 2 5 3 1]
 [6 4 3 9 1 5 7 8 2]
 [9 7 2 8 6 3 1 4 5]
 [8 5 1 4 2 7 6 9 3]
 [1 3 4 7 8 9 2 5 6]
 [2 6 8 3 5 1 9 7 4]
 [7 9 5 2 4 6 3 1 8]]
more??
[[3 1 6 5 7 8 4 9 2]
 [5 2 9 1 3 4 7 6 8]
 [4 8 7 6 2 9 5 3 1]
 [2 6 3 4 1 5 9 8 7]
 [9 7 4 8 6 3 1 2 5]
 [8 5 1 7 9 2 6 4 3]
 [1 3 8 9 4 7 2 5 6]
 [6 9 2 3 5 1 8 7 4]
 [7 4 5 2 8 6 3 1 9]]
more??
[[3 1 6 5 7 8 4 9 2]
 [5 2 9 1 3 4 7 6 8]
 [4 8 7 6 9 2 5 3 1]
 [2 6 3 4 1 5 9 8 7]
 [9 7 4 8 6 3 1 2 5]
 [8 5 1 7 2 9 6 4 3]
 [1 3 8 9 4 7 2 5 6]
 [6 9 2 3 5 1 8 7 4]
 [7 4 5 2 8 6 3 1 9]]
more??
[[3 1 6 5 7 8 4 9 2]
 [5 2 9 1 3 4 7 6 8]
 [4 8 7 6 9 2 5 3 1]
 [2 6 3 4 1 5 9 8 7]
 [9 7 4 8 6 3 1 2 5]
 [8 5 1 9 2 7 6 4 3]
 [1 3 8 7 4 9 2 5 6]
 [6 9 2 3 5 1 8 7 4]
 [7 4 5 2 8 6 3 1 9]]
more??
[[3 1 6 5 8 7 4 2 9]
 [5 2 9 1 3 4 8 6 7]
 [4 8 7 6 2 9 5 3 1]
 [6 4 3 9 1 5 7 8 2]
 [9 7 2 8 6 3 1 4 5]
 [8 5 1 4 7 2 6 9 3]
 [1 3 4 7 9 8 2 5 6]
 [2 6 8 3 5 1 9 7 4]
 [7 9 5 2 4 6 3 1 8]]
more??


In [25]:
def printmat():
        for i in range(9):
            for j in range(9):
                    print(grid[i][j]," ",end="")
            print() 

In [33]:
printmat()

3  0  6  5  0  8  4  0  0  
5  2  0  0  0  0  0  0  0  
0  8  7  0  0  0  0  3  1  
0  0  3  0  1  0  0  8  0  
9  0  0  8  6  3  0  0  5  
0  5  0  0  9  0  6  0  0  
1  3  0  0  0  0  2  5  0  
0  0  0  0  0  0  0  7  4  
0  0  5  2  0  6  3  0  0  


In [35]:
check(0,1,1)

True